version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=topicos2
      - POSTGRES_PASSWORD=123456
    ports:
      - '5431:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data
volumes:
  db:
    driver: local